### ISSUE TITLE
Show only hits that have image

### ISSUE THREAD

**Issue by thomashrabe** [GodzikLab/FlexModServer#3]
Hide cluster members that do not have an thumbnail for now until we understand why they are missing

**Comment by sanshu** [comment]
Fixed by commit fff54ae

**Comment by thomashrabe** [comment]
I am not sure if it's solved. I pulled the recent changes and now it's showing all pictures from RCSB. Pleas check http://modflex.org

**Comment by sanshu** [comment]
You might need to do hard reload of the page. Works for different sequences on my mac.

**Comment by thomashrabe** [comment]
Tried, it displays images for each row now. However, the origin of each image seems to be RSCB, not our thumbnails? For each pdbid that I randomly pick and look at the image on RSCB the images look identical. I believe the fix now automatically overrides existing thumbnails?

**Comment by sanshu** [comment]
I guess CORS is not enabled, in this case it will pull image from PDB for every protein.

Check JS errors, I see bunch of 404s for our “default” sequence.

**Comment by thomashrabe** [comment]
Not sure why, but I see it’s looking for double URL

http://modflex.org/thumbnails/http://modflex.org/thumbnails/3vndF.3vndA.jpgFailed to load resource: the server responded with a status of 404 (Not Found)

**Comment by sanshu** [comment]
I don't see double URLs
![screen shot 2017-02-09 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/3451613/22806410/ca6942b8-eed6-11e6-952c-58d512086bff.png)

**Comment by sanshu** [comment]
Try to clear cache may be?

**Comment by sanshu** [comment]
Oh, now I got the same error. Will fix.

**Comment by thomashrabe** [comment]
This whole caching issue sucks when developing... :) 

From the road

**Comment by thomashrabe** [comment]
Safari:
http://apple.stackexchange.com/questions/250247/permanently-disable-safari-caches/250265

Empty the cache from the Develop menu.
Quit Safari.
Lock ~/Library/Caches/com.apple.Safari/Cache.db from Finder's Get Info inspector.
This prevents Safari writing to the cache.

Chrome:
http://stackoverflow.com/questions/5690269/disabling-chrome-cache-for-website-development

**Comment by sanshu** [comment]
Pushed. Cannot test it locally due to cross domain errors.

**Comment by thomashrabe** [comment]
Now the whole URL is missing

Failed to load resource: the server responded with a status of 404 (Not Found) 3vndF.3vndA.jpg

**Comment by sanshu** [comment]
Hm. on my side it loads some thumbs
![screen shot 2017-02-09 at 3 19 16 pm](https://cloud.githubusercontent.com/assets/3451613/22807339/41e02542-eedb-11e6-8e65-2897d5a774eb.png)

**Comment by sanshu** [comment]
Can you send html for the element with this url?

**Comment by thomashrabe** [comment]
Now it works for me… ?
I dont understand the caching issues, but now looks alright.
