### ISSUE TITLE
Calculate intermediate models between 2 PDBs

### ISSUE THREAD

**Issue by carrieaz** [GodzikLab/FlexModServer#6]
### This is note for reference.
Purpose: when one click on a pair of PDBs in the rmsd matrix, it will calculate the ddm between them and generate a list of intermediate structures between them.

Pipeline: 

- launch http://pdbflex.org/php/runDDM.php?pdbs=1a5sA,1xcfB&jobID=12345
- runDDM.php will execute a local script to generate the ddm and pdb files between the input pair of PDBs. After it finishes it will output a jason file with information of the results (file names and url locations)
`{
    "jobDir": "12345.JGJQtO",
    "PDB1": "1a5sA.pdb",
    "PDB2": "1xcfB.pdb",
    "ddmMat": "1a5sA.1xcfB.ddm",
    "ddmPDB": "1a5sA.1xcfB.pdb",
    "ddmGif": "1a5sA.1xcfB.gif",
    "urlRoot": "/data/tmp/pdbflexTMP"
}`
- Modflex can access the intermediate PDB by  `http://pdbflex.org/data/tmp/pdbflexTMP/12345.swZPuu/1a5sA.1xcfB.pdb`
To display the intermediate PDBs, include the javascripts http://pdbflex.org/js/3dmolService.js 
- "PDB1", "PDB2" and "ddmPDB" are in the same coordinate system. 
-  Replace the correct jobDir in the URL

**Comment by lukaszgit** [comment]
This would be great !

But it does not work yet, right ?

best

Lukasz

**Comment by carrieaz** [comment]
Yes.  It works.

**Comment by lukaszgit** [comment]
Hi,

I got response but it seems that PDBs I got are empty.

best,

Lukasz

**Comment by carrieaz** [comment]
Could you let me know the link with the PDBs which gave empty result?   Maybe the input PDB file does not exist in PDBflex.

**Comment by lukaszgit** [comment]
Hi,

I get this json here: http://pdbflex.org/php/runDDM.php?pdbs=1a5sA,1xcfB&jobID=12345
but then when I try pdbflex.org/data/tmp/pdbflexTMP/12345.R0cHr5/1a5sA.1xcfB.pdb
I get empty pdb.

maybe I make some mistake with my browser ?

best

Lukasz

**Comment by lukaszgit** [comment]
Hi Mayya,

I don’t know how much your are able to work these days with school issues etc.
- let me know. I can try to help.

After fixing some minor bug Zhanwen’s runDDM.php script below works now
so we can work on adding animation to modflex.

best

Lukasz

**Comment by lukaszgit** [comment]
Adding models of the query protein built on the intermediate structures between two templates

So far after a user clicks a cell in RMSD (comparison) matrix,
modflex prepares intermediate structures and shows a 3dmol animations. 

Now it can also show a button “Build models on intermediate structures” or something like that.
 
Once clicked this button should call:
 
http://pdbflex.org/php/modDDM.php?sequence=NEPEKMLAALKVFVQPMKAATRS&tmp_d=177.lvhzPi
 
(where a sequence should be the original query sequence submitted to modflex and tmp_d would be a full directory name
returned earlier by runDDM.php which was called when matrix cell was clicked)
 
modDDM.php should return an object with some job info but status of modeling can be checked
at http://pdbflex.org/data/tmp/pdbflexTMP/177.lvhzPi/mod.ddm/status.txt
 
Once it says “Modelling complete” models of a query sequence built on intermediate structures between
two selected templates can be downloaded at: http://pdbflex.org/data/tmp/pdbflexTMP/177.lvhzPi/mod.ddm/mod.ddm.pdb
 
let me know if it requires any changes and let’s see if it would work

**Comment by sanshu** [comment]
This is an old repository, I'll close this issue and reference it from current repo.

**Comment by lukaszgit** [comment]
You are right
L
